apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        # Using the official pre-built image until your CI pipeline handles the builds
        image: dockersamples/examplevotingapp_worker
